input_dir: ./input
output_dir: ./output
exp_dir: ./output/experiments
features_dir: ./output/features
preprocess_dir: ./output/preprocess
candidate_dir: ./output/preprocess/make_candidate

gcs_bucket: gs://recsys2024/murakami